platform :ios, '13.0'

target 'Runner' do
  use_frameworks! :linkage => :static

  # --- 暴力修复：直接在本地定义 peertalk 的规格 ---
  pod 'peertalk', :podspec => {
    :name => 'peertalk',
    :version => '1.0.0',
    :summary => 'iOS USB communication',
    :homepage => 'https://github.com/rsms/peertalk',
    :license => 'MIT',
    :authors => { 'rsms' => 'rsms' },
    :source => { :git => 'https://github.com/rsms/peertalk.git', :tag => 'master' },
    :source_files => 'peertalk/*.{h,m}',
    :public_header_files => 'peertalk/*.h',
    :requires_arc => true,
    :platforms => { :ios => '13.0' }
  }

  # 自动加载其他 Flutter 插件（如果存在）
  begin
    setup_path = File.expand_path(File.join('..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)
    if File.exist?(setup_path)
      require setup_path
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end
  rescue => e
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      # 确保头文件路径能被找到
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/peertalk'
    end
  end
end
