platform :ios, '13.0'

target 'Runner' do
  use_frameworks! :linkage => :static

  # 1. 强制引用本地路径，不给 CocoaPods 任何报错的机会
  pod 'peertalk', :path => 'peertalk_local'

  # 2. 这里的脚本只在本地环境存在时才运行，Codemagic 环境下会因我们手动创建了 xcconfig 而跳过报错
  begin
    setup_path = File.expand_path(File.join('..', '..', 'packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)
    if File.exist?(setup_path)
      require setup_path
      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end
  rescue => e
    # 静默处理
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
